import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [
    {
      type: 'link',
      label: 'News',
      href: '/blog/tags/news'
    },
    {
      type: 'link',
      label: 'Maintenance Info',
      href: '/blog/tags/maintenance'
    },
    {
      type: 'link',
      label: 'Full-text Search',
      href: 'https://sc.ddbj.nig.ac.jp/search'
    },

    {type: 'autogenerated', dirName: 'guides'},

    {
      type: 'link',
      label: 'Github Discussions',
      href: 'https://github.com/nig-sc/nigsc_homepage2/discussions'
    },
    

  ],
  applicationSidebar: [{type: 'autogenerated', dirName: 'application'}],
  advancedGuidesSidebar: [{type: 'autogenerated', dirName: 'advanced_guides'}],
  operationSidebar: [{type: 'autogenerated', dirName: 'operation'}],
  reportSidebar: [{type: 'autogenerated', dirName: 'report'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
