/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
  */

    topSidebar: {
        "お知らせ": [
            "news/2021_0512_shortQ設定変更",
            "news/過去のお知らせ"
        ],
        "障害情報": [
            "news2/2021_0722_qlogin",
            "news2/2021_0602_network",
            "news2/過去の障害情報"
        ],
        "システム構成": [
            "guides/top",
            "guides/divisions",
            "guides/hardware",
            "software/software"
        ],
        "一般解析区画の使い方": [
            "general_analysis_division/ga_introduction",
            "general_analysis_division/ga_application",
            "general_analysis_division/ga_login",
            "general_analysis_division/ga_usage",
            "general_analysis_division/ga_transfer",
            "general_analysis_division/ga_lustre",
        ],
        "個人ゲノム解析区画の使い方": [
            "personal_genome_division/pg_introduction",
            "personal_genome_division/pg_application",
            "personal_genome_division/pg_login",
            "personal_genome_division/pg_usage",
            "personal_genome_division/pg_transfer",
            "general_analysis_division/ga_lustre",
        ],
        "稼働状況": [
            "operation/operation",
            "operation/gfree",
        ],
    },
    softwareSidebar: {
        "ジョブスケジューラ": [
            "software/univa_grid_engine",
            "software/slurm"
        ],
        "コンテナ・解析パイプライン": [
            "software/Singularity",
        ],
        "開発環境・ライブラリ": [
            "software/python",
            "software/R",
            "software/jupyter_notebook",
            "software/jupyter_lab",
            "software/java",
            "software/typescript",
            "software/rust",
        ]
    },
    applicationsSidebar : {
        "利用規定等": [
            "application/application",
            "application/use_policy",
            "application/legislation"
        ],
        "ユーザー登録・変更": [
            "application/registration",
            "application/resource_extension",
            "application/ssh_keys",
            "application/renewal",
        ],
        "課金サービス利用方法": [
            "application/billing_service",
            "application/invoice",
            "application/price_list",
        ],
        "お問い合わせ等": [
            "faq/faq1",
            "application/reference"
        ],
    },
    advancedGuidesSidebar : {
        "活用方法": [
            "advanced_guides/advanced_guide",
        ],
    },
    reportSidebar: {
        "成果報告(2020.01.01--2020.12.31)": [
            "report/report_2020",
            "report/papers_2020",
        ],
        "成果報告(2019.01.01--2019.12.31)": [
            "report/report_2019",
            "report/papers_2019",
        ],

    }

};
