name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push with Kaniko
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            gcr.io/kaniko-project/executor:latest \
            --context=/workspace \
            --dockerfile=/workspace/Dockerfile \
            --destination=10.99.82.64:5000/nigsc-homepage:${{ github.sha }} \
            --destination=10.99.82.64:5000/nigsc-homepage:latest \
            --insecure
