name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: actions/cache@v3
      id: node_modules_cache_id
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm ci
    - run: npm run build --if-present
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
